### ISSUE TITLE
rename "raters" by "owners"

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#20] opened 2016-11-04 18:05 UTC
Did I understood you correct to rename raters by members to ensure consistency in the wording

**Comment by ursmeier-mercatus** [comment] 2016-11-04 18:08
Yes. 
Raters (no more "members")
and 
Ratings (no more "rates")

**Comment by ursmeier-mercatus** [comment] 2016-11-06 21:37
duplicate of #33 
closing

**Closed as completed by ursmeier-mercatus** 2016-11-06 21:37 UTC
Labels: ios, android, Feature Request Prio 1
