### ISSUE TITLE
Wrong number of feasable rates in case the start date is in the past and is more than the defined frequency

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#82] opened 2016-12-09 20:50 UTC
Rates in the past longer than the defined frequency shouldn't be accepted.

![2016-12-09 21_45_02-](https://cloud.githubusercontent.com/assets/22747157/21064035/0734d3a0-be59-11e6-8af3-29752d624e16.png)

This bug can't be accepted for the first productive release as too many rates are listed in the past.

![2016-12-09 21_49_13-](https://cloud.githubusercontent.com/assets/22747157/21064101/607361a2-be59-11e6-8032-ab4c0daa64c2.png)

**Comment by ursmeier-mercatus** [comment] 2016-12-10 07:45
duplicate of #81, same issue. Closing.

**Closed as completed by ursmeier-mercatus** 2016-12-10 07:45 UTC
Labels: bug
